version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin-server
    user: "${PUID}:${PGID}"
    network_mode: "host"
    volumes:
      - "/projects/mediaserver/config:/config"
      - "/projects/mediaserver/cache:/cache"
      - "/mnt/media:/media"
    environment:
      - TZ=Europe/Tallinn
    restart: unless-stopped
